# REQUIRED CONFIG
BOT_TOKEN = "7125001663:AAEQwnDCYJgx1AOHqDvYIseAWRCeREeXgL8"
OWNER_ID = 180233110
TELEGRAM_API = 4659955
TELEGRAM_HASH = "87cf756fb82ec908a63544a04f3fd088"

# SEMI-REQUIRED, WE SUGGEST TO FILL IT FROM MONGODB
DATABASE_URL = "mongodb+srv://sivabdrip2:SzGiOahiSm2VRX5U@cluster0.hpvpe.mongodb.net/?retryWrites=true&w=majority"

# OPTIONAL CONFIG
USER_SESSION_STRING = "AgBHGvMAjufqGy3EJHRwcpZyvmLYwn8n9XZUyTn_1Y15cscpwWpxw977ocCZdALPiIdTAKrzEKdQb7wf7YlSsBUY9bp2NWcDaS1NHC9hJRdgaS74oII_091puCuALbt7CRtRbfef3kFPFq8FVWstRI6RGaO1NZrYocSVwbWSz-AGAJ1K1M-WcMMHbOPSSP1d-lhC9XtUtACW17vBKMpZYh-sUitcXQ6NJFMTeYfuQC03dbGAYzbJzyYtSI3Ko2IqHTq-WyGl1UL6XyRNfFCT7eciF01QlK7ikcE-jhfxDcDuYyomRJeXCMizzYcexgL6RerLihe2CGh_9ZzNmUVbeWlpdbRr-AAAAAAKviOWAA"
DOWNLOAD_DIR = "/usr/src/app/downloads/"
CMD_SUFFIX = ""
AUTHORIZED_CHATS = "-1001692026506 -1001735678862"
SUDO_USERS = "180233110 919042541"
DEFAULT_UPLOAD = "gd"
FILELION_API = ""
STREAMWISH_API = ""
EXTENSION_FILTER = ""
INCOMPLETE_TASK_NOTIFIER = False
YT_DLP_OPTIONS = ""
USE_SERVICE_ACCOUNTS = False
NAME_SUBSTITUTE = ""
FFMPEG_CMDS = {}

# INKYPINKY
DELETE_LINKS = False
FSUB_IDS = ""
TOKEN_TIMEOUT = 0
PAID_CHANNEL_ID = 0
PAID_CHANNEL_LINK = ""
SET_COMMANDS = True
METADATA_KEY = ""
WATERMARK_KEY = ""
LOG_CHAT_ID = 0
LEECH_FILENAME_CAPTION = ""

# GDrive Tools
GDRIVE_ID = "1T3Esef6chJdSlyIoFFlygB7A-UwNpRjp"
IS_TEAM_DRIVE = True
STOP_DUPLICATE = True
INDEX_URL = "https://cvam.teamhdt1.workers.dev/0:/mltb/"

# Rclone
RCLONE_PATH = ""
RCLONE_FLAGS = ""
RCLONE_SERVE_URL = ""
RCLONE_SERVE_PORT = 0
RCLONE_SERVE_USER = ""
RCLONE_SERVE_PASS = ""

# Mega credentials
MEGA_EMAIL = ""
MEGA_PASSWORD = ""

# Update
UPSTREAM_REPO = "https://github.com/AeonOrg/Aeon-MLTB"
UPSTREAM_BRANCH = "main"

# Leech
LEECH_SPLIT_SIZE = 0
AS_DOCUMENT = True
MEDIA_GROUP = False
USER_TRANSMISSION = True
MIXED_LEECH = True
LEECH_FILENAME_PREFIX = ""
LEECH_DUMP_CHAT = "-1001935820049"
THUMBNAIL_LAYOUT = ""

# qBittorrent/Aria2c
TORRENT_TIMEOUT = 0
BASE_URL = "http://185.170.112.86:68"
BASE_URL_PORT = 68
WEB_PINCODE = False

# Queueing system
QUEUE_ALL = 0
QUEUE_DOWNLOAD = 0
QUEUE_UPLOAD = 0

# RSS
RSS_DELAY = 600
RSS_CHAT = ""
RSS_SIZE_LIMIT = 0
