fix = true
unsafe-fixes = true
line-length = 85
target-version = "py313"

[lint.mccabe]
max-complexity = 100

[lint]
select = [
    "E",        # pycodestyle: error
    "F",        # pyflakes
    "I",        # isort
    "W",        # pycodestyle: warning
    "B",        # flake8-bugbear
    "N",        # pep8-naming
    "C4",       # flake8-comprehensions
    "UP",       # pyupgrade
    "FA",       # flake8-future-annotations
    "PL",       # pylint
    "PIE",      # flake8-pie
    "PYI",      # flake8-pyi
    "RET",      # flake8-return
    "RUF",      # ruff
    "SIM",      # flake8-simplify
    "TCH",      # flake8-type-checking
    "TID",      # flake8-tidy-imports
    "ARG",      # flake8-unused-arguments
    "C90",      # mccabe
    "COM",      # flake8-commas
    "FURB",     # refurb
    "PERF",     # perflint
    "ASYNC",    # flake8-async
]

ignore = [
    "E501",
    "F403",
    "N801",
    "N806",
    "N818",
    "PLR09",
    "RUF002",
    "SIM115",
    "PERF203",
    "PLR0912",
    "PLR0913",
    "PLR0915",
    "PLR2004",
    "PLR1702",
    "PLW1514",
    "PLW2901",
]
